## Use Case: Fitness data analysis



In [ ]:
import numpy as np
data = np.loadtxt('step_tracker.txt', dtype='str')
print(data)

['Date,UserID,Steps,Distance_km,Calories,ActiveMinutes,SleepHours'
 '2025-07-01,U101,8234,6.2,320,45,6.5'
 '2025-07-01,U102,10234,7.8,410,60,7.0'
 '2025-07-02,U101,7890,6.0,300,50,6.0'
 '2025-07-02,U102,11000,8.4,440,65,7.2'
 '2025-07-03,U101,8500,6.5,325,47,6.8'
 '2025-07-03,U102,12050,9.0,470,70,7.5']


The step data for 7 days is: [3450, 6780, 4560, 8900, 12000, 4300, 5100]. Convert it into a NumPy array and print the average steps taken.

In [ ]:
steps = np.array([8234,10234,7890,11000,8500,12050])
print(steps)
b = np.mean(steps)
print(b) 

[ 8234 10234  7890 11000  8500 12050]
9651.333333333334


How many days did the user walk more than 5000 steps?


In [ ]:
steps_days = np.sum(steps > 5000)
print('days' ,steps_days)

days 6


Replace all days with less than 5000 steps with the value 5000 and print the new array.


In [ ]:
import numpy as np

steps = np.array([3450, 6780, 4560, 8900, 12000, 4300, 5100])

# Replace values less than 5000 with 5000
steps[steps < 5000] = 5000

print('Updated steps:', steps)


Updated steps: [ 5000  6780  5000  8900 12000  5000  5100]


Nutrition Analyzer


You work on a nutrition app that stores calorie intake for 5 days. Each row represents a day, and columns represent: [breakfast, lunch, dinner].





calories = [

[350, 700, 650],

[400, 680, 620],

[300, 710, 640],

[500, 690, 660],

[420, 730, 610]

]


In [ ]:
import numpy as np

calories = np.array([ 
    
            [350, 700, 650],

            [400, 680, 620],

            [300, 710, 640],

            [500, 690, 660],

            [420, 730, 610]]
           )

print('calories data' , calories)


calories data [[350 700 650]
 [400 680 620]
 [300 710 640]
 [500 690 660]
 [420 730 610]]


Convert this into a NumPy array and print the shape and data type.

In [ ]:
a = calories.shape
b = calories.dtype
print(a ,b)

(5, 3) int64


What's the shape of the data?

Print the total calories consumed each day.


In [ ]:
a = calories.sum()

print(a ,b)

8660 int64


Find the day number (starting from 1) with the highest total calories.

In [ ]:
import numpy as np

calories = np.array([320, 410, 300, 440, 325, 470])

# Find the index of the highest calorie value
max_day_index = np.argmax(calories)

# Add 1 since days start from 1
day_number = max_day_index + 1

print("Day with highest calories is Day", day_number)


Day with highest calories is Day 6


School Test Scores

scores = [

[78, 85, 90],

[88, 79, 93],

[84, 76, 89],

[90, 88, 91]

]


Find the day number (starting from 1) with the highest total calories.

In [ ]:
import numpy as np

scores = np.array([

            [78, 85, 90],

            [88, 79, 93],

            [84, 76, 89],

            [90, 88, 91]

            ])

print("score array" , scores)


score array [[78 85 90]
 [88 79 93]
 [84 76 89]
 [90 88 91]]


Convert to NumPy array and print the average score per student.

In [ ]:
import numpy as np

scores = np.array([
    [78, 85, 90],
    [88, 79, 93],
    [84, 76, 89],
    [90, 88, 91]
])

# Calculate average per student (along axis=1)
average_scores = np.mean(scores, axis=1)

print("Average score per student:", average_scores)


Average score per student: [84.33333333 86.66666667 83.         89.66666667]


School Test Scores

In [ ]:
#Print the average score per test.

average_scores = np.mean(scores,axis=0)
print("Average score per student:", average_scores)


Average score per student: [85.   82.   90.75]


In [ ]:
#Print the average score per test.

average_scores = np.mean(scores,axis=0)
print("Average score per student:", average_scores)


Average score per student: [85.   82.   90.75]


In [ ]:
#What was Student 2’s score in Test 3?
average_scores = scores[1,2]
print(average_scores)

93


In [ ]:
#Replace all scores below 80 with 80 (pass mark updated).
scores[scores <80] = 80
print(scores)

[[80 85 90]
 [88 80 93]
 [84 80 89]
 [90 88 91]]


#Convert to a NumPy array and print the total number of orders.

orders = [120, 135, 98, 150, 143, 160, 170, 129, 140, 132]

Convert to a NumPy array and print the total number of orders.

Increase orders on weekend days (index 5 and 6) by 20%, and print the updated array.

What is the new average daily orders?


In [6]:
import numpy as np

orders = np.array([120, 135, 98, 150, 143, 160, 170, 129, 140, 132])
print(orders)

orders_sum = np.sum(orders)
print("total no of orders" , orders_sum)

orders[5] = orders[5] * 20
orders[6] = orders[6] * 20
print(orders)

orders_mean = np.mean(orders)
print(orders_mean)

[120 135  98 150 143 160 170 129 140 132]
total no of orders 1377
[ 120  135   98  150  143 3200 3400  129  140  132]
764.7


Movie Rating Platform
Five users rated five movies. Rows represent users, columns represent movies.





ratings = [

[7, 8, 6, 5, 9],

[6, 5, 8, 7, 7],

[9, 7, 6, 8, 6],

[5, 6, 7, 7, 8],

[8, 9, 5, 6, 7]

]

Convert to NumPy array and print the average rating for each movie.

Which movie (index) received the highest average rating?

Replace all ratings below 6 with 6 (enforcing a minimum rating).


In [15]:
import numpy as np

ratings  =np.array([[7, 8, 6, 5, 9],

                    [6, 5, 8, 7, 7],

                    [9, 7, 6, 8, 6],

                    [5, 6, 7, 7, 8],

                    [8, 9, 5, 6, 7]
                    ])

print("ratings array" , ratings)

ratings_mean = np.mean(ratings ,axis=0)
print("average rating for eeach movie" , ratings_mean)

ratings_highest = np.argmax(ratings)
print("higest rating for each movie" , ratings_highest)

ratings[ratings < 6] = 6
print("beloe 6 rating" , ratings)

ratings array [[7 8 6 5 9]
 [6 5 8 7 7]
 [9 7 6 8 6]
 [5 6 7 7 8]
 [8 9 5 6 7]]
average rating for eeach movie [7.  7.  6.4 6.6 7.4]
higest rating for each movie 4
beloe 6 rating [[7 8 6 6 9]
 [6 6 8 7 7]
 [9 7 6 8 6]
 [6 6 7 7 8]
 [8 9 6 6 7]]


Your expenses over 7 days across 3 categories: [food, travel, shopping].





expenses = [

[320, 150, 400],

[450, 120, 300],

[370, 180, 500],

[410, 160, 200],

[300, 140, 450],

[360, 130, 420],

[390, 170, 380]

]

Convert to NumPy array. Print the total expenses per category.

Find the day with the highest travel expense.

Extract only the shopping expenses as a 1D array.

Normalize all expenses (divide all values by 100 and round to 1 decimal).








In [22]:
import numpy as np

monthly_expense  =np.array([

[320, 150, 400],

[450, 120, 300],

[370, 180, 500],

[410, 160, 200],

[300, 140, 450],

[360, 130, 420],

[390, 170, 380]

]
)

print("monthly expense array" , monthly_expense)

monthly_expense_mean = np.mean(monthly_expense,axis=0)
print("average monthly expense" , monthly_expense_mean)

highest_travel = np.argmax(monthly_expense[:],1)
print("highest travel expense month" , highest_travel)

round_expense = np.round(monthly_expense /100 ,1 )
print(round_expense)

monthly expense array [[320 150 400]
 [450 120 300]
 [370 180 500]
 [410 160 200]
 [300 140 450]
 [360 130 420]
 [390 170 380]]
average monthly expense [371.42857143 150.         378.57142857]
highest travel expense month [2 0 2 0 2 2 0]
[[3.2 1.5 4. ]
 [4.5 1.2 3. ]
 [3.7 1.8 5. ]
 [4.1 1.6 2. ]
 [3.  1.4 4.5]
 [3.6 1.3 4.2]
 [3.9 1.7 3.8]]
